"""align schema: money NUMERIC, add FKs, drop dead columns

Revision ID: 6d83ed464bd3
Revises: 2da689c6b79b
Create Date: 2026-07-20 18:53:23.882050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d83ed464bd3'
down_revision: Union[str, None] = '2da689c6b79b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ---- 数据清洗（先于加外键，否则脏数据会让约束创建失败）----
    # 1) 孤儿附件：指向不存在的交易
    op.execute("DELETE FROM attachments WHERE transaction_id NOT IN (SELECT id FROM transactions)")
    # 2) 空串哨兵一律转 NULL（外键约束下空串会违约）
    op.execute("UPDATE categories SET parent_id=NULL WHERE parent_id=''")
    op.execute("UPDATE transactions SET account_id=NULL WHERE account_id=''")
    op.execute("UPDATE transactions SET category_id=NULL WHERE category_id=''")
    op.execute("UPDATE transactions SET to_account_id=NULL WHERE to_account_id=''")
    op.execute("UPDATE transactions SET contact_id=NULL WHERE contact_id=''")
    op.execute("UPDATE transactions SET reimbursement_batch_id=NULL WHERE reimbursement_batch_id=''")
    op.execute("UPDATE invoices SET transaction_id=NULL WHERE transaction_id=''")
    op.execute("UPDATE salary_records SET transaction_id=NULL WHERE transaction_id=''")
    op.execute("UPDATE recurring_expenses SET category_id=NULL WHERE category_id=''")
    op.execute("UPDATE recurring_expenses SET account_id=NULL WHERE account_id=''")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('initial_balance',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_attachments_transaction_id_transactions'), 'transactions', ['transaction_id'], ['id'])

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('alert_threshold',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=6, scale=4),
               existing_nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_budgets_category_id_categories'), 'categories', ['category_id'], ['id'])
        batch_op.drop_column('spent')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_categories_parent_id_categories'), 'categories', ['parent_id'], ['id'])

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('base_salary',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('social_insurance_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=6, scale=4),
               existing_nullable=False)
        batch_op.alter_column('housing_fund_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=6, scale=4),
               existing_nullable=False)
        batch_op.alter_column('special_deduction',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('self_tax_filing',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('tax_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('total_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_invoices_transaction_id_transactions'), 'transactions', ['transaction_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('recurring_expenses', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_recurring_expenses_category_id_categories'), 'categories', ['category_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_recurring_expenses_account_id_accounts'), 'accounts', ['account_id'], ['id'])

    with op.batch_alter_table('reimbursement_batches', schema=None) as batch_op:
        batch_op.alter_column('total_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('actual_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('fee',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.create_unique_constraint(batch_op.f('uq_reimbursement_batches_batch_no'), ['batch_no'])
        batch_op.drop_column('payment_confirmed_at')
        batch_op.drop_column('payment_confirmed')

    with op.batch_alter_table('salary_records', schema=None) as batch_op:
        batch_op.alter_column('base_salary',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('tax',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('net_salary',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.drop_index('uq_salary_employee_year_month')
        batch_op.create_unique_constraint('uq_salary_employee_year_month', ['employee_id', 'year', 'month'])
        batch_op.create_foreign_key(batch_op.f('fk_salary_records_transaction_id_transactions'), 'transactions', ['transaction_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_salary_records_employee_id_employees'), 'employees', ['employee_id'], ['id'])
        batch_op.drop_column('status')

    with op.batch_alter_table('tax_settings', schema=None) as batch_op:
        batch_op.alter_column('vat_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=6, scale=4),
               existing_nullable=False)
        batch_op.alter_column('vat_threshold_quarterly',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('additional_tax_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=6, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('category_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('account_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('invoice_issued',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        # 旧库 DEFAULT "[]" 用了双引号（SQLite 视为标识符、重建表时报"非常量默认值"），
        # 借本次重建改为单引号常量 '[]'
        batch_op.alter_column('invoice_images',
               existing_type=sa.TEXT(),
               nullable=False,
               server_default=sa.text("'[]'"))
        batch_op.alter_column('company_account_images',
               existing_type=sa.TEXT(),
               nullable=False,
               server_default=sa.text("'[]'"))
        batch_op.create_foreign_key(batch_op.f('fk_transactions_to_account_id_accounts'), 'accounts', ['to_account_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_transactions_category_id_categories'), 'categories', ['category_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_transactions_account_id_accounts'), 'accounts', ['account_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_transactions_contact_id_contacts'), 'contacts', ['contact_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_transactions_reimbursement_batch_id_reimbursement_batches'), 'reimbursement_batches', ['reimbursement_batch_id'], ['id'])
        batch_op.drop_column('book_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_id', sa.VARCHAR(length=36), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_transactions_reimbursement_batch_id_reimbursement_batches'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_transactions_contact_id_contacts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_transactions_account_id_accounts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_transactions_category_id_categories'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_transactions_to_account_id_accounts'), type_='foreignkey')
        batch_op.alter_column('company_account_images',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text('("[]")'))
        batch_op.alter_column('invoice_images',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text('("[]")'))
        batch_op.alter_column('invoice_issued',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('account_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('category_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('tax_settings', schema=None) as batch_op:
        batch_op.alter_column('additional_tax_rate',
               existing_type=sa.Numeric(precision=6, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('vat_threshold_quarterly',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('vat_rate',
               existing_type=sa.Numeric(precision=6, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('salary_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_salary_records_employee_id_employees'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_salary_records_transaction_id_transactions'), type_='foreignkey')
        batch_op.drop_constraint('uq_salary_employee_year_month', type_='unique')
        batch_op.create_index('uq_salary_employee_year_month', ['employee_id', 'year', 'month'], unique=1)
        batch_op.alter_column('net_salary',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('tax',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('base_salary',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('reimbursement_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_confirmed', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('payment_confirmed_at', sa.VARCHAR(length=30), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_reimbursement_batches_batch_no'), type_='unique')
        batch_op.alter_column('fee',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('actual_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('recurring_expenses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_recurring_expenses_account_id_accounts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_recurring_expenses_category_id_categories'), type_='foreignkey')
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_invoices_transaction_id_transactions'), type_='foreignkey')
        batch_op.alter_column('total_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('tax_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('self_tax_filing',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('special_deduction',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('housing_fund_rate',
               existing_type=sa.Numeric(precision=6, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('social_insurance_rate',
               existing_type=sa.Numeric(precision=6, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('base_salary',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_categories_parent_id_categories'), type_='foreignkey')

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spent', sa.FLOAT(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_budgets_category_id_categories'), type_='foreignkey')
        batch_op.alter_column('alert_threshold',
               existing_type=sa.Numeric(precision=6, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_attachments_transaction_id_transactions'), type_='foreignkey')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('initial_balance',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('balance',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
