"""add structured link columns payout_batch_id / salary_record_id

Revision ID: 7d40ade50fb5
Revises: 6d83ed464bd3
Create Date: 2026-07-20 19:05:46.699444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d40ade50fb5'
down_revision: Union[str, None] = '6d83ed464bd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payout_batch_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('salary_record_id', sa.String(length=36), nullable=True))
        batch_op.create_index('ix_transactions_payout_batch_id', ['payout_batch_id'], unique=False)
        batch_op.create_index('ix_transactions_salary_record_id', ['salary_record_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_transactions_payout_batch_id_reimbursement_batches'), 'reimbursement_batches', ['payout_batch_id'], ['id'])

    # ### end Alembic commands ###

    # ---- 存量回填：把 [RB:]/[SR:] 描述标记解析进结构化列 ----
    # [RB:批次号] 打款流水 → payout_batch_id
    op.execute("""
        UPDATE transactions SET payout_batch_id = (
            SELECT b.id FROM reimbursement_batches b
            WHERE transactions.description LIKE '[RB:' || b.batch_no || ']%'
        )
        WHERE description LIKE '[RB:%'
    """)
    # [SR:记录ID] 差额流水 → salary_record_id（仅回填能对上真实记录的）
    op.execute("""
        UPDATE transactions SET salary_record_id = (
            SELECT s.id FROM salary_records s
            WHERE transactions.description LIKE '%[SR:' || s.id || ']%'
        )
        WHERE description LIKE '%[SR:%'
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transactions_payout_batch_id_reimbursement_batches'), type_='foreignkey')
        batch_op.drop_index('ix_transactions_salary_record_id')
        batch_op.drop_index('ix_transactions_payout_batch_id')
        batch_op.drop_column('salary_record_id')
        batch_op.drop_column('payout_batch_id')

    # ### end Alembic commands ###
